version: '3'
services:
  elasticsearch:
    image: registry.cn-hangzhou.aliyuncs.com/ripper/elasticsearch:8.14.2
    container_name: elasticsearch
    tty: true
    restart: always
    privileged: true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
      - ./plugins:/usr/share/elasticsearch/plugins
      - ./config/certs/elastic-certificates.p12:/usr/share/elasticsearch/config/certs/elastic-certificates.p12
    environment:
      - TZ=Asia/Shanghai
      - ES_JAVA_OPTS=-Xmx2g -Xms2g
      - ELASTIC_PASSWORD=123456
    networks:
      - es
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: registry.cn-hangzhou.aliyuncs.com/ripper/kibana:8.14.2
    container_name: kibana
    tty: true
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - es
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G

networks:
  es:
    name: es
    driver: bridge